basePath: /api/v1
definitions:
  models.CreateJobRequest:
    properties:
      department:
        type: string
      description:
        type: string
      job_item:
        type: string
      locations:
        items:
          type: string
        type: array
    type: object
  utils.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Optii API server.
  title: Optii API
  version: v1
paths:
  /job:
    post:
      consumes:
      - application/json
      description: create new job
      parameters:
      - description: Create Job
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/models.CreateJobRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateJobRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Create an job
      tags:
      - job
swagger: "2.0"
